{"aid": "iln9qwxd1n313g", "result": {"folders": ["工具使用", "lab1"], "unique_views": 91, "request_instructor_me": false, "change_log": [{"data": "il7so2j1g60eq", "anon": "no", "when": "2016-02-29T09:39:58Z", "uid": "i14g50r7ui12pn", "type": "create"}, {"to": "il7so2iy2c9ep", "anon": "no", "when": "2016-02-29T13:07:21Z", "uid": "i6w84pnmjCQ", "type": "followup"}, {"to": "il7so2iy2c9ep", "anon": "no", "when": "2016-02-29T13:34:06Z", "uid": "i0et95bli7r7ky", "type": "followup"}], "upvote_ids": [], "id": "il7so2iy2c9ep", "bookmarked": 5, "no_answer": 1, "i_edits": [], "is_bookmarked": false, "children": [{"folders": [], "updated": "2016-02-29T13:07:21Z", "no_upvotes": 0, "uid": "i6w84pnmjCQ", "created": "2016-02-29T13:07:21Z", "type": "followup", "no_answer": 1, "id": "il802re0qsr34h", "anon": "no", "bucket_name": "Today", "config": {}, "bucket_order": 2, "data": null, "children": [], "subject": "<p></p>\n<p>&#43;1&#xff0c;按照下面这个的说法</p>\n<p>http://stackoverflow.com/questions/7986139/git-error-when-trying-to-push-pre-receive-hook-declined</p>\n<p>可能是因为助教还没修好服务器所以拒绝了&#xff1f;求解释</p>"}, {"folders": [], "updated": "2016-02-29T13:34:06Z", "no_upvotes": 0, "uid": "i0et95bli7r7ky", "created": "2016-02-29T13:34:06Z", "type": "followup", "no_answer": 1, "id": "il8115tjyc1bm", "anon": "no", "bucket_name": "Today", "config": {}, "bucket_order": 2, "data": null, "children": [], "subject": "<p>&#43;1 遇到一样的问题</p>"}], "no_answer_followup": 2, "nr": 636, "bucket_order": 2, "config": {}, "status": "active", "tags": ["lab1", "student", "unanswered", "工具使用"], "num_favorites": 0, "bucket_name": "Today", "q_edits": [], "data": {"embed_links": []}, "request_instructor": 0, "created": "2016-02-29T09:39:58Z", "is_tag_good": false, "type": "question", "s_edits": [], "my_favorite": false, "default_anonymity": "no", "t": 1457674477105, "tag_good": [{"name": "Long Haomin", "admin": false, "photo": null, "us": false, "email": "cherudim9@gmail.com", "role": "student", "facebook_id": null, "id": "i14g50r7ui12pn"}], "tag_good_arr": ["i14g50r7ui12pn"], "history": [{"content": "<p>无论是docker的webshell还是自己连vpn&#xff0c;在使用git push命令时都会遇到失败&#xff1a;</p>\n<pre>Warning: Permanently added &#39;172.16.13.236&#39; (ECDSA) to the list of known hosts.                                                            \nCounting objects: 3, done.                                                                                                                \nWriting objects: 100% (3/3), 204 bytes | 0 bytes/s, done.                                                                                 \nTotal 3 (delta 0), reused 0 (delta 0)                                                                                                     \nremote: GitLab: The project you were looking for could not be found.                                                                      \nTo git&#64;172.16.13.236:cherudim9/ucore_lab.git                                                                                              \n ! [remote rejected] master -&gt; master (pre-receive hook declined)                                                                         \nerror: failed to push some refs to &#39;git&#64;172.16.13.236:cherudim9/ucore_lab.git&#39;  </pre>\n<p>按照往年的帖子&#xff0c;还有网上的解答&#xff0c;试图通过修改project setting中的protect_branch&#xff0c;但是没法进入这个页面&#xff0c;会直接转到project的首页。。</p>", "anon": "no", "subject": "无法push到gitlab&#xff1a;“ ! [remote rejected] master -&gt; master (pre-receive hook declined)    ”", "uid": "i14g50r7ui12pn", "created": "2016-02-29T09:39:58Z"}]}, "error": null}